//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress.DevAV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://igsappprod/IGSWebApi/api/AppSettings")]
        public global::System.Uri EnvironmentUri {
            get {
                return ((global::System.Uri)(this["EnvironmentUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Production")]
        public string CurrentService {
            get {
                return ((string)(this["CurrentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://igsappdev/IGSWebApi/api/AppSettings")]
        public global::System.Uri Development {
            get {
                return ((global::System.Uri)(this["Development"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://igsappdr/IGSWebApi/api/AppSettings")]
        public global::System.Uri Test {
            get {
                return ((global::System.Uri)(this["Test"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cc967897-w/IGSWebApi/api/AppSettings")]
        public global::System.Uri Production {
            get {
                return ((global::System.Uri)(this["Production"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfFilterInfo xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <FilterInfo>
              <Name>All Customers</Name>
              <FilterCriteria />
            </FilterInfo>
            <FilterInfo>
              <Name>My Account</Name>
              <FilterCriteria>[HomeOffice.State] = ##Enum#DevExpress.DevAV.StateEnum,CA#</FilterCriteria>
            </FilterInfo>
            <FilterInfo>
              <Name>John's Account</Name>
              <FilterCriteria>[HomeOffice.State] = ##Enum#DevExpress.DevAV.StateEnum,WA#</FilterCriteria>
            </FilterInfo>
            <FilterInfo>
              <Name>Top Stores</Name>
              <FilterCriteria>[AnnualRevenue] &gt;= 90000000000.0m</FilterCriteria>
            </FilterInfo>
          </ArrayOfFilterInfo>
        ")]
        public global::DevExpress.DevAV.ViewModels.FilterInfoList CustomersCustomFilters {
            get {
                return ((global::DevExpress.DevAV.ViewModels.FilterInfoList)(this["CustomersCustomFilters"]));
            }
            set {
                this["CustomersCustomFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfFilterInfo xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <FilterInfo>
              <Name>HD Video player</Name>
              <FilterCriteria>Contains([Name], 'HD') And Category = 'VideoPlayers'</FilterCriteria>
            </FilterInfo>
            <FilterInfo>
              <Name>50inch Plasma</Name>
              <FilterCriteria>Contains([Name], '50') And Category = 'Televisions'</FilterCriteria>
            </FilterInfo>
            <FilterInfo>
              <Name>21inch Monitor</Name>
              <FilterCriteria>Contains([Name], '21') And Category = 'Monitors'</FilterCriteria>
            </FilterInfo>
            <FilterInfo>
              <Name>Remote Control</Name>
              <FilterCriteria>Contains([Name], 'Remote') And Category = 'Automation'</FilterCriteria>
            </FilterInfo>
          </ArrayOfFilterInfo>
        ")]
        public global::DevExpress.DevAV.ViewModels.FilterInfoList ProductsCustomFilters {
            get {
                return ((global::DevExpress.DevAV.ViewModels.FilterInfoList)(this["ProductsCustomFilters"]));
            }
            set {
                this["ProductsCustomFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          <ArrayOfFilterInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instan" +
            "ce\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n            <FilterInfo>\r\n   " +
            "           <Name>All</Name>\r\n              <ImageUri>Resources/Products/All.png<" +
            "/ImageUri>\r\n            </FilterInfo>\r\n            <FilterInfo>\r\n              <" +
            "Name>Video Players</Name>\r\n              <FilterCriteria>[Category] = ##Enum#Dev" +
            "Express.DevAV.ProductCategory,VideoPlayers#</FilterCriteria>\r\n              <Ima" +
            "geUri>Resources/Products/VideoPlayers.png</ImageUri>\r\n            </FilterInfo>\r" +
            "\n            <FilterInfo>\r\n              <Name>Automation</Name>\r\n              " +
            "<FilterCriteria>[Category] = ##Enum#DevExpress.DevAV.ProductCategory,Automation#" +
            "</FilterCriteria>\r\n              <ImageUri>Resources/Products/Automation.png</Im" +
            "ageUri>\r\n            </FilterInfo>\r\n            <FilterInfo>\r\n              <Nam" +
            "e>Monitors</Name>\r\n              <FilterCriteria>[Category] = ##Enum#DevExpress." +
            "DevAV.ProductCategory,Monitors#</FilterCriteria>\r\n              <ImageUri>Resour" +
            "ces/Products/Monitors.png</ImageUri>\r\n            </FilterInfo>\r\n            <Fi" +
            "lterInfo>\r\n              <Name>Projectors</Name>\r\n              <FilterCriteria>" +
            "[Category] = ##Enum#DevExpress.DevAV.ProductCategory,Projectors#</FilterCriteria" +
            ">\r\n              <ImageUri>Resources/Products/Projectors.png</ImageUri>\r\n       " +
            "     </FilterInfo>\r\n            <FilterInfo>\r\n              <Name>Televisions</N" +
            "ame>\r\n              <FilterCriteria>[Category] = ##Enum#DevExpress.DevAV.Product" +
            "Category,Televisions#</FilterCriteria>\r\n              <ImageUri>Resources/Produc" +
            "ts/TVs.png</ImageUri>\r\n            </FilterInfo>\r\n          </ArrayOfFilterInfo>" +
            "\r\n        ")]
        public global::DevExpress.DevAV.ViewModels.FilterInfoList ProductsStaticFilters {
            get {
                return ((global::DevExpress.DevAV.ViewModels.FilterInfoList)(this["ProductsStaticFilters"]));
            }
            set {
                this["ProductsStaticFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          <ArrayOfFilterInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instan" +
            "ce\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n            <FilterInfo>\r\n   " +
            "           <Name>All Tasks</Name>\r\n              <FilterCriteria />\r\n           " +
            "   <ImageUri>Resources/Tasks/InProgress.png</ImageUri>\r\n            </FilterInfo" +
            ">\r\n            <FilterInfo>\r\n              <Name>In Progress</Name>\r\n           " +
            "   <FilterCriteria>[Status] = ##Enum#DevExpress.DevAV.EmployeeTaskStatus,InProgr" +
            "ess#</FilterCriteria>\r\n              <ImageUri>Resources/Tasks/InProgress.png</I" +
            "mageUri>\r\n            </FilterInfo>\r\n            <FilterInfo>\r\n              <Na" +
            "me>Not Started</Name>\r\n              <FilterCriteria>[Status] = ##Enum#DevExpres" +
            "s.DevAV.EmployeeTaskStatus,NotStarted#</FilterCriteria>\r\n              <ImageUri" +
            ">Resources/Tasks/NotStarted.png</ImageUri>\r\n            </FilterInfo>\r\n         " +
            "   <FilterInfo>\r\n              <Name>Deferred</Name>\r\n              <FilterCrite" +
            "ria>[Status] = ##Enum#DevExpress.DevAV.EmployeeTaskStatus,Deferred#</FilterCrite" +
            "ria>\r\n              <ImageUri>Resources/Tasks/Deferred.png</ImageUri>\r\n         " +
            "   </FilterInfo>\r\n            <FilterInfo>\r\n              <Name>Completed</Name>" +
            "\r\n              <FilterCriteria>[Status] = ##Enum#DevExpress.DevAV.EmployeeTaskS" +
            "tatus,Completed#</FilterCriteria>\r\n              <ImageUri>Resources/Tasks/Compl" +
            "eted.png</ImageUri>\r\n            </FilterInfo>\r\n            <FilterInfo>\r\n      " +
            "        <Name>High Priority</Name>\r\n              <FilterCriteria>[Priority] = #" +
            "#Enum#DevExpress.DevAV.EmployeeTaskPriority,High#</FilterCriteria>\r\n            " +
            "  <ImageUri>Resources/Tasks/HighPriority.png</ImageUri>\r\n            </FilterInf" +
            "o>\r\n            <FilterInfo>\r\n              <Name>Urgent</Name>\r\n              <" +
            "FilterCriteria>[Priority] = ##Enum#DevExpress.DevAV.EmployeeTaskPriority,Urgent#" +
            "</FilterCriteria>\r\n              <ImageUri>Resources/Tasks/Urgent.png</ImageUri>" +
            "\r\n            </FilterInfo>\r\n          </ArrayOfFilterInfo>\r\n        ")]
        public global::DevExpress.DevAV.ViewModels.FilterInfoList TasksStaticFilters {
            get {
                return ((global::DevExpress.DevAV.ViewModels.FilterInfoList)(this["TasksStaticFilters"]));
            }
            set {
                this["TasksStaticFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfFilterInfo xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <FilterInfo>
    <Name>All</Name>
    <ImageUri>Resources/Employees/All.png</ImageUri>
  </FilterInfo>
  <FilterInfo>
    <Name>Salaried</Name>
    <FilterCriteria>[Status] = ##Enum#DevExpress.DevAV.EmployeeStatus,Salaried#</FilterCriteria>
    <ImageUri>Resources/Employees/Salaried.png</ImageUri>
  </FilterInfo>
  <FilterInfo>
    <Name>Commission</Name>
    <FilterCriteria>[Status] = ##Enum#DevExpress.DevAV.EmployeeStatus,Commission#</FilterCriteria>
    <ImageUri>Resources/Employees/Commission.png</ImageUri>
  </FilterInfo>
  <FilterInfo>
    <Name>Contract</Name>
    <FilterCriteria>[Status] = ##Enum#DevExpress.DevAV.EmployeeStatus,Contract#</FilterCriteria>
    <ImageUri>Resources/Employees/Probation.png</ImageUri>
  </FilterInfo>
  <FilterInfo>
    <Name>Terminated</Name>
    <FilterCriteria>[Status] = ##Enum#DevExpress.DevAV.EmployeeStatus,Terminated#</FilterCriteria>
    <ImageUri>Resources/Employees/Terminated.png</ImageUri>
  </FilterInfo>
  <FilterInfo>
    <Name>On Leave</Name>
    <FilterCriteria>[Status] = ##Enum#DevExpress.DevAV.EmployeeStatus,OnLeave#</FilterCriteria>
    <ImageUri>Resources/Employees/OnLeave.png</ImageUri>
  </FilterInfo>
</ArrayOfFilterInfo>")]
        public global::DevExpress.DevAV.ViewModels.FilterInfoList EmployeesStaticFilters {
            get {
                return ((global::DevExpress.DevAV.ViewModels.FilterInfoList)(this["EmployeesStaticFilters"]));
            }
            set {
                this["EmployeesStaticFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfFilterInfo xmlns:xsi=\"http://www" +
            ".w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n" +
            " </ArrayOfFilterInfo>")]
        public global::DevExpress.DevAV.ViewModels.FilterInfoList AppSettingsDetailStaticFilters {
            get {
                return ((global::DevExpress.DevAV.ViewModels.FilterInfoList)(this["AppSettingsDetailStaticFilters"]));
            }
            set {
                this["AppSettingsDetailStaticFilters"] = value;
            }
        }
    }
}
